apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: time
  name: time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
      - image: kiselev/time
        name: time
        ports:
        - containerPort: 8080

